In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [21]:
df=sns.load_dataset('tips')
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [7]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [11]:
df.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [15]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split


In [19]:
lab_enc=LabelEncoder()

In [23]:
df1=lab_enc.fit_transform(df['sex'])
df['sex']=df1
df1=lab_enc.fit_transform(df['time'])
df['time']=df1
df1=lab_enc.fit_transform(df['day'])
df['day']=df1
df1=lab_enc.fit_transform(df['smoker'])
df['smoker']=df1

In [29]:
x = df.drop('total_bill',axis = 1)

In [31]:
y = df[['total_bill']]

In [33]:
scaler = StandardScaler()

In [35]:
x_scaled = scaler.fit_transform(x)
x_scaled

array([[-1.43994695e+00, -1.34335316e+00, -7.84789169e-01,
         2.79157595e-01, -6.21581561e-01, -6.00192629e-01],
       [-9.69205340e-01,  7.44405889e-01, -7.84789169e-01,
         2.79157595e-01, -6.21581561e-01,  4.53382921e-01],
       [ 3.63355539e-01,  7.44405889e-01, -7.84789169e-01,
         2.79157595e-01, -6.21581561e-01,  4.53382921e-01],
       ...,
       [-7.22971264e-01,  7.44405889e-01,  1.27422758e+00,
        -8.02024201e-01, -6.21581561e-01, -6.00192629e-01],
       [-9.04025732e-01,  7.44405889e-01, -7.84789169e-01,
        -8.02024201e-01, -6.21581561e-01, -6.00192629e-01],
       [ 1.24660453e-03, -1.34335316e+00, -7.84789169e-01,
         1.36033939e+00, -6.21581561e-01, -6.00192629e-01]])

In [37]:
x_train,x_test,y_train,y_test = train_test_split(x_scaled,y,test_size = 0.3 , random_state = 42)

# Decision Tree Regressor

In [39]:
from sklearn.tree import DecisionTreeRegressor

In [41]:
d_tree=DecisionTreeRegressor()

In [45]:
d_tree.fit(x_scaled,y)

DecisionTreeRegressor()

In [47]:
x_dtree=d_tree.predict(x_test)
x_dtree

array([19.82      , 11.90333333, 20.27      , 25.89      , 13.        ,
       16.185     , 28.44      , 12.48      , 14.78      , 15.38      ,
       18.165     , 10.77      , 10.05666667, 16.185     , 10.07      ,
       18.64      , 18.71      , 21.58      , 16.45      , 41.19      ,
       20.69      , 20.65      , 14.31      ,  9.55      , 19.525     ,
       11.69      , 10.27      , 25.28      , 20.27      , 48.17      ,
       38.07      ,  7.74      , 17.81      , 20.29      , 16.97      ,
       24.08      , 12.03      , 43.11      , 13.16      , 18.24      ,
       10.29      , 12.528     , 23.95      , 10.33      , 13.28333333,
        3.07      , 10.59      , 18.69      ,  7.56      , 13.28      ,
       24.27      , 27.28      , 31.71      , 15.98      , 19.49      ,
       12.16333333,  7.25      , 17.82      , 17.26      , 15.69      ,
       29.85      , 17.31      , 23.33      , 16.27      , 20.23      ,
       20.92      , 15.01      ,  7.25      , 26.59      , 24.52

In [49]:
y_dtree=d_tree.predict(x_train)
y_dtree

array([15.53      , 20.45      , 34.65      , 25.29      , 38.37      ,
       29.8       ,  9.78      , 25.71      , 20.08      , 10.05666667,
       38.37      , 16.21      , 18.35      , 15.42      , 24.06      ,
       21.7       , 13.94      , 29.03      ,  8.52      , 16.32      ,
       17.51      , 10.29      , 40.17      , 17.47      , 16.58      ,
       17.92      , 17.46      , 18.24      , 15.98      , 21.96      ,
       16.43      , 13.03      , 10.29      , 13.27      , 23.17      ,
       15.48      , 16.99      , 21.01      , 27.2       , 22.23      ,
       11.35      , 12.528     , 11.87      , 32.9       , 24.99      ,
       34.83      , 50.81      , 13.09      , 24.99      , 16.31      ,
       27.05      , 18.24      , 15.77      , 12.43      , 13.39      ,
       12.528     , 35.26      , 35.83      , 13.03      , 13.09      ,
       24.59      , 14.26      , 17.355     , 34.3       , 31.85      ,
       13.28333333, 11.02      ,  8.51      , 12.528     , 12.16

In [63]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
r2_score(y_train,y_dtree)

0.9813403974607355

In [65]:
r2_score(y_test,x_dtree)

0.9827202539807958

In [71]:
mean_absolute_error(y_test,x_dtree)

0.4046441441441441

In [73]:
mean_squared_error(y_test,x_dtree)

1.203643695195195